### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by walliski** [enricostara/telegram.link#1]
Hi

Was thinking about making an irc->Telegram gateway, and found this to be looking interesting? Is the project status up to date with the readme, or how far have you come?

Thanks,
Walliski

**Comment by francisbrito** [comment]
:+1: to @rousso1's comment. This project is precisely what I was looking for!

**Comment by m-derevyanko** [comment]
I'm waiting for the first work version too :)

**Comment by enricostara** [comment]
Hi, I'm currently working on the EncryptedMessage, it's the corner stone for every communication with Mtproto. I hope to write code again on regular basis

**Comment by elad** [comment]
@enricostara please post a todo list of sorts, I'd like to help with the coding. I'm very interested in having an MIT-licensed API to Telegram.

**Comment by enricostara** [comment]
Hi, 
a first working version should be released soon

- the EncryptedMessage was released and unit tested. 
- the telegram.link and the sub-projects introduced the "channel" for remote procedure call. Now the auth-key generation uses an unencrypted channel (RpcChannel class) to execute the Type functions needed to complete that process.
- Now I'm writing the EncrypedRpcChannel class (that uses EncryptedMessage) in order to execute theoretically any Type Function declared in the Telegram API set and dynamically built by the TypeBuilder class.

I'm thinking how to involve coders interested to have a complete and working project.

A key point could be creating a straightforward client project (on GitHub, MIT licensed) that uses telegram.link in a real context in order to code the major use cases and test all the functions hard to check without a real time integration with Telegram server.  Basically, we could write something that represents just a good example to develop any kind of telegram-client with telegram.link

**Comment by enricostara** [comment]
thanks! :)

**Comment by kaminoo** [comment]
Awesome stuff @enricostara. Really. Greetings from us here, we are a bunch of people expecting your awesome library to be finished. Let us know if you need any help. The more I read about the MTProto and TL the less I think I understand. Even after reading your code. Ha.

I have a working project on some other platforms, and can't wait to integrate it with Telegram.

I wanted to suggest a wiki page here on github to let us know the status of the project, so we don't bother you here in the issues :)

Regards!

**Comment by kauegimenes** [comment]
:+1: The project looks awsome!

**Comment by enricostara** [comment]
Hi,

the `EncryptedRpcChannel` finally is working and the very first encrypted call  `sendCode` was integrated in the library. 

It's only the first step but I really hope that, starting from this point, add a new feature could be more straightforward..

I added the [Termgram](http://termgram.me) project, in order to provide an 'how to' for the library.
It's a very simple application and it's actually able to ask to Telegram to send the registration code to your phone.
As soon as a new feature will be available in the library it will be exploited and tested by **Termgram**.

**Comment by kaminoo** [comment]
Awesome news!

**Comment by elad** [comment]
@enricostara you are the man, excellent job! And again, if some of the work can be broken down or explained so other folks can jump in and help, please help us help you. :)

**Comment by enricostara** [comment]
Thanks guys! your support inspires me to keep going :)

I think that the whole api is big enough to split this work in more devs, but I need to better shape the framework before

**Comment by meqube** [comment]
@enricostara when do you think that you are finished with building the option to send and receive messages?

**Comment by enricostara** [comment]
I'm near to complete the user authorization, next step should be get the contacts and start to send/receive the text messages

**Comment by pferraris** [comment]
Hi @enricostara! I'm examining telegram.link.
I have added a few methods (auth.signIn and updates.getState) in telegram.link.js, and I have enabled all methods loading in api.js passing a null value for "methods" parameter in buildTypes call.
Calling auth.signIn works fine and I receive auth.Authorization response.
Then, when I call updates.getState, I get an Updates object but tl-node can't deserialize it.
Updates has a Vector<Update>, a Vector<User> & a Vector<Chat> members. When it try deserialize, it instantiate a TypeVector with "options.type = Update" (or User or Chat), TypeVector constructor calls manageType with type name, and it calls requireTypeByName.
As there is no constructor called that way it raises an exception.
Shouldn't require the type by id instead?
If you need more details, let me know.
Thanks and sorry for my English :)

**Comment by enricostara** [comment]
I checked your issue but I don't find the `Updates` and `Vector` types:

https://core.telegram.org/method/updates.getState

Tell me more :)

**Comment by pferraris** [comment]
It's true, updates.GetState must return a updates.State object, but I think this activates the updates mechanism before (https://core.telegram.org/api/updates). So before receiving updates.State object I receive an Updates object.
I'd like to help with the development of this library, because I think that is great.
If you want, I can share the modified code using a pull request.

**Comment by enricostara** [comment]
Ok, good! 
I knew that the Vector needs to use requireTypeById instead of byName, it's mandatory for polymorphic internal type. 
Currently I'm still working on an another deep problem on the protocol (the EncryptedMessage has to use also the MessageContainer type to be able to send more than one msg..) in order to send back the acknowledgement to the server on rcp-result asap.. therefore feel free to pull the request ;)
..and many thanks!

**Comment by kauegimenes** [comment]
@pferraris Awesome to see more contributors! 
I will to find time to help this project in the future!

**Comment by jploh** [comment]
@pferraris - Did you create a pull request? I would like to see what changes you made.

**Comment by enricostara** [comment]
See the last comment on this topic here:
https://github.com/enricostara/telegram.link/wiki/Project-Status
