### ISSUE TITLE
Client not ready!

### ISSUE THREAD

**Issue by mory91** [enricostara/telegram.link#8]
Hello guys....
i keep getting "Client not ready!" error with the code bellow....
anyone know why??
--------------------------------------------------------------
var telegramLink = require('telegram.link')();
var os = require('os');

 var client = telegramLink.createClient(
     {
         id: 11111,       //some id
         hash: '111111111111111111111111', //some hash
         version: '1.0.0',
         lang: 'en',
   		 deviceModel: os.type(),
    	 systemVersion: os.platform() + '/' + os.release()
     },
     telegramLink.PROD_PRIMARY_DC,
     function(ex){
             if(!ex) { console.log('Connected to Telegram!'); }
             else {console.log(ex);}
         }
 );

 var peer = new telegramLink.type.InputPeerContact({
      props: {
           user_id: 'userID'
      }
 });

 client.messages.sendMessage(
      peer,
      'My UTF8 first msg!!',
      '9876543211'  // random id...
 ).then(function(sentMsg) {
      console.log('sentMsg:', sentMsg.toPrintable());
 });

**Comment by fazo96** [comment]
Because you have to wait for it to connect to telegram.
Using your code, you start connecting when you call `createClient` and then you try sending a message right after, but the client isn't connected yet.

You need to send the message after you're connect. you have a function that prints "Connected to Telegram!" when it connects. Send the message from that function so that you're sure that you're connected.

Also you're trying to send a message to "userID" which won't work (obviously) so maybe you can try the function that downloads the contact list.

**Comment by pavelsr** [comment]
Hi Enrico,

My purpose is to know is specified phone registered in Telegram or no. I have same problem when requesting with your library [auth.checkPhone]( https://core.telegram.org/method/auth.checkPhone) method, which even [doesn't requre authorization according API docs](https://core.telegram.org/api/auth).

Here is my script

```javascript
var data = {} // Hold all global data
data.telegramLink = require('../telegram.link')();

data.app = {
   id: 12345,
     hash: '12345678901234567890',
     version: '1.0.0',
     lang: 'en'
};

data.client = data.telegramLink.createClient(data.app, data.telegramLink.TEST_PRIMARY_DC, function(ex){
  if(!ex) { 
    console.log('Connected to Telegram!');
    data.client.auth.checkPhone('79885851900', function (result) {
      console.log(result);
    }); 
  } 
  else { 
    console.log(ex);
  }
```

I have checked and tested [telecommander.js](https://github.com/fazo96/telecommander/blob/master/telecommander.js), it works fine. My code is very similar to it, but I can't figure out what's wrong. 

Please help to correct my code.

**Comment by fazo96** [comment]
I have never used the checkPhone function, are you sure the first argument of its callback is supposed to be the result? maybe it's the error first, then the result.

Also what exactly is the problem? Does it say "Client not ready"? That would be weird...

**Comment by pavelsr** [comment]
@fazo96 yes, it says "Client is not yet ready"

Full log below:

```
pavel@pavel-Inspiron-3542:~/projects/phones_checker$ nodejs main.js 

TELEGRAM.LINK
v.0.6.4

Connected to Telegram!
[ERROR] Wed, 27 Jul 2016 07:19:07 GMT  telegram-link Client is not yet ready!
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Client is not yet ready!
    at Client.isReady (/home/pavel/projects/telegram.link/lib/telegram.link.js:391:28)
    at Object.callService (/home/pavel/projects/telegram.link/lib/utility.js:22:17)
    at Auth.checkPhone (/home/pavel/projects/telegram.link/lib/api/auth.js:114:20)
    at Client.<anonymous> (/home/pavel/projects/phones_checker/main.js:29:19)
    at Client.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Client.emit (events.js:185:7)
    at Timeout._onTimeout (/home/pavel/projects/telegram.link/lib/utility.js:58:26)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

I have two guessings:
1) telegram.link library doesn't allow to use auth.checkPhone method without authorization (however according [API docs](https://core.telegram.org/api/auth) it's possible)
2) auth.checkPhone method [return a Promise](https://rawgit.com/enricostara/telegram.link/master/doc/api/auth.html#section-26) and I'm dealing with promises not correct way.

**Comment by fazo96** [comment]
I took a quick look at @enricostara's code, and it looks like he wrote telegram link in a very declarative way, checkPhone is called like every other telegram API call, and the "Client is not ready!" error is returned because there is no channel to communicate with telegram with.

Looks like telegram.link doesn't support using the API while not authorized, and implementing it doesn't look easy. I think it needs a way to connect without authorization. Your function call won't work because there is no communication channel with telegram.

I'm sorry, but this doesn't look like an easy fix to me, but I might be totally wrong since I'm not familiar with this code base

**Comment by farhadamjady** [comment]
you should set authKey true as argument however its optional!
